language: cpp

script:
  - make test doc

compiler:
  - gcc
#  - clang

dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - graphviz

env:
  global:
    - MAKEFLAGS="-j 2"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: src/doc/html
  on:
    branch: master
    condition: "$CC = gcc"
