language: cpp

script:
  - make
  - make testD
  - make doc
  - if [ $CC = gcc ]; then ./get_code_cov.sh; fi

after_success:
  - if [ $CC = gcc ]; then bash <(curl -s https://codecov.io/bash); fi

compiler:
  - gcc
  - clang

env:
  global:
    - MAKEFLAGS="-j 4"

dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - graphviz

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: src/doc/html
  on:
    branch: master
    condition: "$CC = gcc"
